spring:
  application:
    name: web
  zipkin:
    service:
      name: web-service
    sender:
      type: web
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8080
logging:
  level:
    ROOT: WARN
    ru.bms: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus