version: '3.3'

services:
  client-service:
    image: 192.168.4.176:5000/bmsgroup/client-service:${TAG}
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    volumes:
      - ./client-service/docker/config:/config
    configs:
      - source: client_config
        target: /config/client-service.yml

configs:
  client_config:
    file: ./client-service/docker/config/client-service.yml