version: '3.3'

services:
  client-service:
    image: 192.168.4.176:5000/bmsgroup/client-service:${TAG}
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    configs:
      - source: client_config
        target: /config/client-service.yml
  handler-service:
    image: bmsgroup/handler-service
    build:
      context: ./handler-service
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    configs:
      - source: handler_config
        target: /config/handler-service.yml
  payment-service:
    image: bmsgroup/payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    configs:
      - source: payment_config
        target: /config/payment-service.yml
  terminal-service:
    image: bmsgroup/terminal-service
    build:
      context: ./terminal-service
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    configs:
      - source: terminal_config
        target: /config/terminal-service.yml
  web-service:
    image: bmsgroup/web-service
    build:
      context: ./web-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: web_config
        target: /config/web-service.yml
  zipkin:
    image: bmsgroup/zipkin
    build:
      context: ./zipkin
      dockerfile: Dockerfile
    ports:
      - 9411:9411
    configs:
      - source: zipkin_config
        target: /config/zipkin.yml
  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    configs:
      - source: grafana_config
        target: /etc/grafana/provisioning/datasource.yml
  prometheus:
    image: prom/prometheus:$PROMETHEUS_VERSION
    ports:
      - 9090:9090
    configs:
      - source: grafana_config
        target: /etc/prometheus/prometheus.yml

configs:
  client_config:
    file: ./client-service/docker/config/client-service.yml
  handler_config:
    file: ./handler-service/docker/config/handler-service.yml
  payment-config:
    file: ./payment-service/docker/config/payment-config.yml
  terminal-config:
    file: ./terminal-service/docker/config/terminal-config.yml
  web-config:
    file: ./web-service/docker/config/web-config.yml
  zipkin-config:
    file: ./zipkin/docker/config/zipkin.yml
  grafana-config:
    file: ./Prometheus/config/grafana/provisioning/datasources/datasource.yml
  prometheus-config:
    file: ./Prometheus/config/prometheus/prometheus.yml
