version: '3.3'

services:
  client-service:
    image: 192.168.4.176:5000/bmsgroup/client-service:${TAG}
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    configs:
      - source: client_config
        target: /config/client-service.yml
  handler-service:
    image:  192.168.4.176:5000/bmsgroup/handler-service:${TAG}
    build:
      context: ./handler-service
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    configs:
      - source: handler_config
        target: /config/handler-service.yml
  payment-service:
    image:  192.168.4.176:5000/bmsgroup/payment-service:${TAG}
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    configs:
      - source: payment_config
        target: /config/payment-service.yml
  terminal-service:
    image:  192.168.4.176:5000/bmsgroup/terminal-service:${TAG}
    build:
      context: ./terminal-service
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    configs:
      - source: terminal_config
        target: /config/terminal-service.yml
  web-service:
    image:  192.168.4.176:5000/bmsgroup/web-service:${TAG}
    build:
      context: ./web-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: web_config
        target: /config/web-service.yml
  zipkin:
    image:  192.168.4.176:5000/bmsgroup/zipkin:${TAG}
    build:
      context: ./zipkin
      dockerfile: Dockerfile
    ports:
      - 9411:9411
    configs:
      - source: zipkin_config
        target: /config/zipkin.yml
  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    configs:
      - source: grafana_config
        target: /etc/grafana/provisioning/datasource.yml
  prometheus:
    image: prom/prometheus:$PROMETHEUS_VERSION
    ports:
      - 9090:9090
    configs:
      - source: grafana_config
        target: /etc/prometheus/prometheus.yml
  elasticsearch:
    image:  192.168.4.176:5000/bmsgroup/elasticsearch:${TAG}
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    image:  192.168.4.176:5000/bmsgroup/logstash:${TAG}
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline_config
        target: /usr/share/logstash/pipeline/logstash.conf
  kibana:
    image:  192.168.4.176:5000/bmsgroup/kibana:${TAG}
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml

configs:
  client_config:
    file: ./client-service/docker/config/client-service.yml
  handler_config:
    file: ./handler-service/docker/config/handler-service.yml
  payment_config:
    file: ./payment-service/docker/config/payment-config.yml
  terminal_config:
    file: ./terminal-service/docker/config/terminal-config.yml
  web_config:
    file: ./web-service/docker/config/web-config.yml
  zipkin_config:
    file: ./zipkin/docker/config/zipkin.yml
  grafana_config:
    file: ./Prometheus/config/grafana/provisioning/datasources/datasource.yml
  prometheus_config:
    file: ./Prometheus/config/prometheus/prometheus.yml
  elasticsearch_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline_config:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
