spring:
  application:
    name: handler
  zipkin:
    service:
      name: handler-service
    sender:
      type: web
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG