spring:
  application:
    name: terminal
  zipkin:
    service:
      name: terminal-service
    sender:
      type: web
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8080
logging:
  level:
    ROOT: WARN
    ru.bms: DEBUG