spring:
  application:
    name: payment
  zipkin:
    service:
      name: payment-service
    sender:
      type: web
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    ROOT: WARN
    ru.bms: DEBUG
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: prometheus