simpleWebServer:
  image: bmsgroup/web-service
  ports:
    - 8080:8080
  volumes:
    - ./docker/config:/config
  command: ["/bin/sh", "-c", "while true; do echo 'HTTP/1.1 200 OK\n\nHello World!' | nc -l -p 80; done"]